COLUMN_MAPPING: dict[str, str] = {
    "name": "A",
    "sku": "D",
    "weight_unit": "F",
    "weight_flag": "H",
    "weight_value": "J",
    "length_unit": "T",
    "length_flag": "V",
    "length_value": "X",
    "description": "AH",
    "brand": "AD",
    "manufacturer": "AI",
    "image_path": "AN",
    "volume_unit": "AP",
    "volume_flag": "AR",
    "volume_value": "AT",
    "square_unit": "AV",
    "square_flag": "AZ",
    "square_value": "BB",
    "origin_country": "CK",
}
